# Generated by Django 4.0.4 on 2022-05-20 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_description_listing_sold_listing_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='description',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='sold',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='title',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='type',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='year',
        ),
    ]
